export type ElementData = {
  atomicNumber: number;
  name: string;
  name_bn: string;
  symbol: string;
  mass: number;
  protons: number;
  neutrons: number;
  electrons: number;
  electronConfiguration: number[];
  electronConfiguration_bn: string[];
};

export const elements: ElementData[] = [
  {
    atomicNumber: 1,
    name: 'Hydrogen',
    name_bn: 'হাইড্রোজেন',
    symbol: 'H',
    mass: 1.008,
    protons: 1,
    neutrons: 0,
    electrons: 1,
    electronConfiguration: [1],
    electronConfiguration_bn: ['১'],
  },
  {
    atomicNumber: 2,
    name: 'Helium',
    name_bn: 'হিলিয়াম',
    symbol: 'He',
    mass: 4.0026,
    protons: 2,
    neutrons: 2,
    electrons: 2,
    electronConfiguration: [2],
    electronConfiguration_bn: ['২'],
  },
  {
    atomicNumber: 3,
    name: 'Lithium',
    name_bn: 'লিথিয়াম',
    symbol: 'Li',
    mass: 6.94,
    protons: 3,
    neutrons: 4,
    electrons: 3,
    electronConfiguration: [2, 1],
    electronConfiguration_bn: ['২', '১'],
  },
  {
    atomicNumber: 4,
    name: 'Beryllium',
    name_bn: 'বেরিলিয়াম',
    symbol: 'Be',
    mass: 9.0122,
    protons: 4,
    neutrons: 5,
    electrons: 4,
    electronConfiguration: [2, 2],
    electronConfiguration_bn: ['২', '২'],
  },
  {
    atomicNumber: 5,
    name: 'Boron',
    name_bn: 'বোরন',
    symbol: 'B',
    mass: 10.81,
    protons: 5,
    neutrons: 6,
    electrons: 5,
    electronConfiguration: [2, 3],
    electronConfiguration_bn: ['২', '৩'],
  },
  {
    atomicNumber: 6,
    name: 'Carbon',
    name_bn: 'কার্বন',
    symbol: 'C',
    mass: 12.011,
    protons: 6,
    neutrons: 6,
    electrons: 6,
    electronConfiguration: [2, 4],
    electronConfiguration_bn: ['২', '৪'],
  },
  {
    atomicNumber: 7,
    name: 'Nitrogen',
    name_bn: 'নাইট্রোজেন',
    symbol: 'N',
    mass: 14.007,
    protons: 7,
    neutrons: 7,
    electrons: 7,
    electronConfiguration: [2, 5],
    electronConfiguration_bn: ['২', '৫'],
  },
  {
    atomicNumber: 8,
    name: 'Oxygen',
    name_bn: 'অক্সিজেন',
    symbol: 'O',
    mass: 15.999,
    protons: 8,
    neutrons: 8,
    electrons: 8,
    electronConfiguration: [2, 6],
    electronConfiguration_bn: ['২', '৬'],
  },
   {
    atomicNumber: 9,
    name: 'Fluorine',
    name_bn: 'ফ্লোরিন',
    symbol: 'F',
    mass: 18.998,
    protons: 9,
    neutrons: 10,
    electrons: 9,
    electronConfiguration: [2, 7],
    electronConfiguration_bn: ['২', '৭'],
  },
  {
    atomicNumber: 10,
    name: 'Neon',
    name_bn: 'নিয়ন',
    symbol: 'Ne',
    mass: 20.180,
    protons: 10,
    neutrons: 10,
    electrons: 10,
    electronConfiguration: [2, 8],
    electronConfiguration_bn: ['২', '৮'],
  },
];
