export type ElementData = {
  atomicNumber: number;
  name: string;
  name_bn: string;
  symbol: string;
  mass: number;
  protons: number;
  neutrons: number;
  electrons: number;
  electronConfiguration: number[];
  electronConfiguration_bn: string[];
};

export const elements: ElementData[] = [
  {
    atomicNumber: 1,
    name: 'Hydrogen',
    name_bn: 'হাইড্রোজেন',
    symbol: 'H',
    mass: 1.008,
    protons: 1,
    neutrons: 0,
    electrons: 1,
    electronConfiguration: [1],
    electronConfiguration_bn: ['১'],
  },
  {
    atomicNumber: 2,
    name: 'Helium',
    name_bn: 'হিলিয়াম',
    symbol: 'He',
    mass: 4.0026,
    protons: 2,
    neutrons: 2,
    electrons: 2,
    electronConfiguration: [2],
    electronConfiguration_bn: ['২'],
  },
  {
    atomicNumber: 3,
    name: 'Lithium',
    name_bn: 'লিথিয়াম',
    symbol: 'Li',
    mass: 6.94,
    protons: 3,
    neutrons: 4,
    electrons: 3,
    electronConfiguration: [2, 1],
    electronConfiguration_bn: ['২', '১'],
  },
  {
    atomicNumber: 4,
    name: 'Beryllium',
    name_bn: 'বেরিলিয়াম',
    symbol: 'Be',
    mass: 9.0122,
    protons: 4,
    neutrons: 5,
    electrons: 4,
    electronConfiguration: [2, 2],
    electronConfiguration_bn: ['২', '২'],
  },
  {
    atomicNumber: 5,
    name: 'Boron',
    name_bn: 'বোরন',
    symbol: 'B',
    mass: 10.81,
    protons: 5,
    neutrons: 6,
    electrons: 5,
    electronConfiguration: [2, 3],
    electronConfiguration_bn: ['২', '৩'],
  },
  {
    atomicNumber: 6,
    name: 'Carbon',
    name_bn: 'কার্বন',
    symbol: 'C',
    mass: 12.011,
    protons: 6,
    neutrons: 6,
    electrons: 6,
    electronConfiguration: [2, 4],
    electronConfiguration_bn: ['২', '৪'],
  },
  {
    atomicNumber: 7,
    name: 'Nitrogen',
    name_bn: 'নাইট্রোজেন',
    symbol: 'N',
    mass: 14.007,
    protons: 7,
    neutrons: 7,
    electrons: 7,
    electronConfiguration: [2, 5],
    electronConfiguration_bn: ['২', '৫'],
  },
  {
    atomicNumber: 8,
    name: 'Oxygen',
    name_bn: 'অক্সিজেন',
    symbol: 'O',
    mass: 15.999,
    protons: 8,
    neutrons: 8,
    electrons: 8,
    electronConfiguration: [2, 6],
    electronConfiguration_bn: ['২', '৬'],
  },
   {
    atomicNumber: 9,
    name: 'Fluorine',
    name_bn: 'ফ্লোরিন',
    symbol: 'F',
    mass: 18.998,
    protons: 9,
    neutrons: 10,
    electrons: 9,
    electronConfiguration: [2, 7],
    electronConfiguration_bn: ['২', '৭'],
  },
  {
    atomicNumber: 10,
    name: 'Neon',
    name_bn: 'নিয়ন',
    symbol: 'Ne',
    mass: 20.180,
    protons: 10,
    neutrons: 10,
    electrons: 10,
    electronConfiguration: [2, 8],
    electronConfiguration_bn: ['২', '৮'],
  },
  {
    atomicNumber: 11,
    name: 'Sodium',
    name_bn: 'সোডিয়াম',
    symbol: 'Na',
    mass: 22.990,
    protons: 11,
    neutrons: 12,
    electrons: 11,
    electronConfiguration: [2, 8, 1],
    electronConfiguration_bn: ['২', '৮', '১'],
  },
  {
    atomicNumber: 12,
    name: 'Magnesium',
    name_bn: 'ম্যাগনেসিয়াম',
    symbol: 'Mg',
    mass: 24.305,
    protons: 12,
    neutrons: 12,
    electrons: 12,
    electronConfiguration: [2, 8, 2],
    electronConfiguration_bn: ['২', '৮', '২'],
  },
  {
    atomicNumber: 13,
    name: 'Aluminium',
    name_bn: 'অ্যালুমিনিয়াম',
    symbol: 'Al',
    mass: 26.982,
    protons: 13,
    neutrons: 14,
    electrons: 13,
    electronConfiguration: [2, 8, 3],
    electronConfiguration_bn: ['২', '৮', '৩'],
  },
  {
    atomicNumber: 14,
    name: 'Silicon',
    name_bn: 'সিলিকন',
    symbol: 'Si',
    mass: 28.085,
    protons: 14,
    neutrons: 14,
    electrons: 14,
    electronConfiguration: [2, 8, 4],
    electronConfiguration_bn: ['২', '৮', '৪'],
  },
  {
    atomicNumber: 15,
    name: 'Phosphorus',
    name_bn: 'ফসফরাস',
    symbol: 'P',
    mass: 30.974,
    protons: 15,
    neutrons: 16,
    electrons: 15,
    electronConfiguration: [2, 8, 5],
    electronConfiguration_bn: ['২', '৮', '৫'],
  },
  {
    atomicNumber: 16,
    name: 'Sulfur',
    name_bn: 'সালফার',
    symbol: 'S',
    mass: 32.06,
    protons: 16,
    neutrons: 16,
    electrons: 16,
    electronConfiguration: [2, 8, 6],
    electronConfiguration_bn: ['২', '৮', '৬'],
  },
  {
    atomicNumber: 17,
    name: 'Chlorine',
    name_bn: 'ক্লোরিন',
    symbol: 'Cl',
    mass: 35.45,
    protons: 17,
    neutrons: 18,
    electrons: 17,
    electronConfiguration: [2, 8, 7],
    electronConfiguration_bn: ['২', '৮', '৭'],
  },
  {
    atomicNumber: 18,
    name: 'Argon',
    name_bn: 'আর্গন',
    symbol: 'Ar',
    mass: 39.948,
    protons: 18,
    neutrons: 22,
    electrons: 18,
    electronConfiguration: [2, 8, 8],
    electronConfiguration_bn: ['২', '৮', '৮'],
  },
  {
    atomicNumber: 19,
    name: 'Potassium',
    name_bn: 'পটাশিয়াম',
    symbol: 'K',
    mass: 39.098,
    protons: 19,
    neutrons: 20,
    electrons: 19,
    electronConfiguration: [2, 8, 8, 1],
    electronConfiguration_bn: ['২', '৮', '৮', '১'],
  },
  {
    atomicNumber: 20,
    name: 'Calcium',
    name_bn: 'ক্যালসিয়াম',
    symbol: 'Ca',
    mass: 40.078,
    protons: 20,
    neutrons: 20,
    electrons: 20,
    electronConfiguration: [2, 8, 8, 2],
    electronConfiguration_bn: ['২', '৮', '৮', '২'],
  },
  {
    atomicNumber: 21,
    name: 'Scandium',
    name_bn: 'স্ক্যান্ডিয়াম',
    symbol: 'Sc',
    mass: 44.956,
    protons: 21,
    neutrons: 24,
    electrons: 21,
    electronConfiguration: [2, 8, 9, 2],
    electronConfiguration_bn: ['২', '৮', '৯', '২'],
  },
  {
    atomicNumber: 22,
    name: 'Titanium',
    name_bn: 'টাইটানিয়াম',
    symbol: 'Ti',
    mass: 47.867,
    protons: 22,
    neutrons: 26,
    electrons: 22,
    electronConfiguration: [2, 8, 10, 2],
    electronConfiguration_bn: ['২', '৮', '১০', '২'],
  },
  {
    atomicNumber: 23,
    name: 'Vanadium',
    name_bn: 'ভ্যানাডিয়াম',
    symbol: 'V',
    mass: 50.942,
    protons: 23,
    neutrons: 28,
    electrons: 23,
    electronConfiguration: [2, 8, 11, 2],
    electronConfiguration_bn: ['২', '৮', '১১', '২'],
  },
  {
    atomicNumber: 24,
    name: 'Chromium',
    name_bn: 'ক্রোমিয়াম',
    symbol: 'Cr',
    mass: 51.996,
    protons: 24,
    neutrons: 28,
    electrons: 24,
    electronConfiguration: [2, 8, 13, 1],
    electronConfiguration_bn: ['২', '৮', '১৩', '১'],
  },
  {
    atomicNumber: 25,
    name: 'Manganese',
    name_bn: 'ম্যাঙ্গানিজ',
    symbol: 'Mn',
    mass: 54.938,
    protons: 25,
    neutrons: 30,
    electrons: 25,
    electronConfiguration: [2, 8, 13, 2],
    electronConfiguration_bn: ['২', '৮', '১৩', '২'],
  },
  {
    atomicNumber: 26,
    name: 'Iron',
    name_bn: 'আয়রন',
    symbol: 'Fe',
    mass: 55.845,
    protons: 26,
    neutrons: 30,
    electrons: 26,
    electronConfiguration: [2, 8, 14, 2],
    electronConfiguration_bn: ['২', '৮', '১৪', '২'],
  },
  {
    atomicNumber: 27,
    name: 'Cobalt',
    name_bn: 'কোবাল্ট',
    symbol: 'Co',
    mass: 58.933,
    protons: 27,
    neutrons: 32,
    electrons: 27,
    electronConfiguration: [2, 8, 15, 2],
    electronConfiguration_bn: ['২', '৮', '১৫', '২'],
  },
  {
    atomicNumber: 28,
    name: 'Nickel',
    name_bn: 'নিকেল',
    symbol: 'Ni',
    mass: 58.693,
    protons: 28,
    neutrons: 31,
    electrons: 28,
    electronConfiguration: [2, 8, 16, 2],
    electronConfiguration_bn: ['২', '৮', '১৬', '২'],
  },
  {
    atomicNumber: 29,
    name: 'Copper',
    name_bn: 'কপার',
    symbol: 'Cu',
    mass: 63.546,
    protons: 29,
    neutrons: 35,
    electrons: 29,
    electronConfiguration: [2, 8, 18, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১'],
  },
  {
    atomicNumber: 30,
    name: 'Zinc',
    name_bn: 'জিংক',
    symbol: 'Zn',
    mass: 65.38,
    protons: 30,
    neutrons: 35,
    electrons: 30,
    electronConfiguration: [2, 8, 18, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২'],
  },
  {
    atomicNumber: 31,
    name: 'Gallium',
    name_bn: 'গ্যালিয়াম',
    symbol: 'Ga',
    mass: 69.723,
    protons: 31,
    neutrons: 39,
    electrons: 31,
    electronConfiguration: [2, 8, 18, 3],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩'],
  },
  {
    atomicNumber: 32,
    name: 'Germanium',
    name_bn: 'জার্মেনিয়াম',
    symbol: 'Ge',
    mass: 72.630,
    protons: 32,
    neutrons: 41,
    electrons: 32,
    electronConfiguration: [2, 8, 18, 4],
    electronConfiguration_bn: ['২', '৮', '১৮', '৪'],
  },
  {
    atomicNumber: 33,
    name: 'Arsenic',
    name_bn: 'আর্সেনিক',
    symbol: 'As',
    mass: 74.922,
    protons: 33,
    neutrons: 42,
    electrons: 33,
    electronConfiguration: [2, 8, 18, 5],
    electronConfiguration_bn: ['২', '৮', '১৮', '৫'],
  },
  {
    atomicNumber: 34,
    name: 'Selenium',
    name_bn: 'সেলেনিয়াম',
    symbol: 'Se',
    mass: 78.971,
    protons: 34,
    neutrons: 45,
    electrons: 34,
    electronConfiguration: [2, 8, 18, 6],
    electronConfiguration_bn: ['২', '৮', '১৮', '৬'],
  },
  {
    atomicNumber: 35,
    name: 'Bromine',
    name_bn: 'ব্রোমিন',
    symbol: 'Br',
    mass: 79.904,
    protons: 35,
    neutrons: 45,
    electrons: 35,
    electronConfiguration: [2, 8, 18, 7],
    electronConfiguration_bn: ['২', '৮', '১৮', '৭'],
  },
  {
    atomicNumber: 36,
    name: 'Krypton',
    name_bn: 'ক্রিপটন',
    symbol: 'Kr',
    mass: 83.798,
    protons: 36,
    neutrons: 48,
    electrons: 36,
    electronConfiguration: [2, 8, 18, 8],
    electronConfiguration_bn: ['২', '৮', '১৮', '৮'],
  },
  {
    atomicNumber: 37,
    name: 'Rubidium',
    name_bn: 'রুবিডিয়াম',
    symbol: 'Rb',
    mass: 85.468,
    protons: 37,
    neutrons: 48,
    electrons: 37,
    electronConfiguration: [2, 8, 18, 8, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '৮', '১'],
  },
  {
    atomicNumber: 38,
    name: 'Strontium',
    name_bn: 'স্ট্রনশিয়াম',
    symbol: 'Sr',
    mass: 87.62,
    protons: 38,
    neutrons: 50,
    electrons: 38,
    electronConfiguration: [2, 8, 18, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৮', '২'],
  },
  {
    atomicNumber: 39,
    name: 'Yttrium',
    name_bn: 'ইট্রিয়াম',
    symbol: 'Y',
    mass: 88.906,
    protons: 39,
    neutrons: 50,
    electrons: 39,
    electronConfiguration: [2, 8, 18, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৯', '২'],
  },
  {
    atomicNumber: 40,
    name: 'Zirconium',
    name_bn: 'জিরকোনিয়াম',
    symbol: 'Zr',
    mass: 91.224,
    protons: 40,
    neutrons: 51,
    electrons: 40,
    electronConfiguration: [2, 8, 18, 10, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১০', '২'],
  },
  {
    atomicNumber: 41,
    name: 'Niobium',
    name_bn: 'নাইওবিয়াম',
    symbol: 'Nb',
    mass: 92.906,
    protons: 41,
    neutrons: 52,
    electrons: 41,
    electronConfiguration: [2, 8, 18, 12, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১২', '১'],
  },
  {
    atomicNumber: 42,
    name: 'Molybdenum',
    name_bn: 'মলিবডেনাম',
    symbol: 'Mo',
    mass: 95.95,
    protons: 42,
    neutrons: 54,
    electrons: 42,
    electronConfiguration: [2, 8, 18, 13, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৩', '১'],
  },
  {
    atomicNumber: 43,
    name: 'Technetium',
    name_bn: 'টেকনেটিয়াম',
    symbol: 'Tc',
    mass: 98,
    protons: 43,
    neutrons: 55,
    electrons: 43,
    electronConfiguration: [2, 8, 18, 13, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৩', '২'],
  },
  {
    atomicNumber: 44,
    name: 'Ruthenium',
    name_bn: 'রুথেনিয়াম',
    symbol: 'Ru',
    mass: 101.07,
    protons: 44,
    neutrons: 57,
    electrons: 44,
    electronConfiguration: [2, 8, 18, 15, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৫', '১'],
  },
  {
    atomicNumber: 45,
    name: 'Rhodium',
    name_bn: 'রোডিয়াম',
    symbol: 'Rh',
    mass: 102.91,
    protons: 45,
    neutrons: 58,
    electrons: 45,
    electronConfiguration: [2, 8, 18, 16, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৬', '১'],
  },
  {
    atomicNumber: 46,
    name: 'Palladium',
    name_bn: 'প্যালাডিয়াম',
    symbol: 'Pd',
    mass: 106.42,
    protons: 46,
    neutrons: 60,
    electrons: 46,
    electronConfiguration: [2, 8, 18, 18],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮'],
  },
  {
    atomicNumber: 47,
    name: 'Silver',
    name_bn: 'সিলভার',
    symbol: 'Ag',
    mass: 107.87,
    protons: 47,
    neutrons: 61,
    electrons: 47,
    electronConfiguration: [2, 8, 18, 18, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '১'],
  },
  {
    atomicNumber: 48,
    name: 'Cadmium',
    name_bn: 'ক্যাডমিয়াম',
    symbol: 'Cd',
    mass: 112.41,
    protons: 48,
    neutrons: 64,
    electrons: 48,
    electronConfiguration: [2, 8, 18, 18, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '২'],
  },
  {
    atomicNumber: 49,
    name: 'Indium',
    name_bn: 'ইন্ডিয়াম',
    symbol: 'In',
    mass: 114.82,
    protons: 49,
    neutrons: 66,
    electrons: 49,
    electronConfiguration: [2, 8, 18, 18, 3],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৩'],
  },
  {
    atomicNumber: 50,
    name: 'Tin',
    name_bn: 'টিন',
    symbol: 'Sn',
    mass: 118.71,
    protons: 50,
    neutrons: 69,
    electrons: 50,
    electronConfiguration: [2, 8, 18, 18, 4],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৪'],
  },
  {
    atomicNumber: 51,
    name: 'Antimony',
    name_bn: 'অ্যান্টিমনি',
    symbol: 'Sb',
    mass: 121.76,
    protons: 51,
    neutrons: 71,
    electrons: 51,
    electronConfiguration: [2, 8, 18, 18, 5],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৫'],
  },
  {
    atomicNumber: 52,
    name: 'Tellurium',
    name_bn: ' টেলুরিয়াম',
    symbol: 'Te',
    mass: 127.60,
    protons: 52,
    neutrons: 76,
    electrons: 52,
    electronConfiguration: [2, 8, 18, 18, 6],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৬'],
  },
  {
    atomicNumber: 53,
    name: 'Iodine',
    name_bn: 'আয়োডিন',
    symbol: 'I',
    mass: 126.90,
    protons: 53,
    neutrons: 74,
    electrons: 53,
    electronConfiguration: [2, 8, 18, 18, 7],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৭'],
  },
  {
    atomicNumber: 54,
    name: 'Xenon',
    name_bn: 'জেনন',
    symbol: 'Xe',
    mass: 131.29,
    protons: 54,
    neutrons: 77,
    electrons: 54,
    electronConfiguration: [2, 8, 18, 18, 8],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৮'],
  },
  {
    atomicNumber: 55,
    name: 'Caesium',
    name_bn: 'সিজিয়াম',
    symbol: 'Cs',
    mass: 132.91,
    protons: 55,
    neutrons: 78,
    electrons: 55,
    electronConfiguration: [2, 8, 18, 18, 8, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৮', '১'],
  },
  {
    atomicNumber: 56,
    name: 'Barium',
    name_bn: 'বেরিয়াম',
    symbol: 'Ba',
    mass: 137.33,
    protons: 56,
    neutrons: 81,
    electrons: 56,
    electronConfiguration: [2, 8, 18, 18, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৮', '২'],
  },
  {
    atomicNumber: 57,
    name: 'Lanthanum',
    name_bn: 'ল্যান্থানাম',
    symbol: 'La',
    mass: 138.91,
    protons: 57,
    neutrons: 82,
    electrons: 57,
    electronConfiguration: [2, 8, 18, 18, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৮', '৯', '২'],
  },
  {
    atomicNumber: 58,
    name: 'Cerium',
    name_bn: 'সিরিয়াম',
    symbol: 'Ce',
    mass: 140.12,
    protons: 58,
    neutrons: 82,
    electrons: 58,
    electronConfiguration: [2, 8, 18, 19, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '১৯', '৯', '২'],
  },
  {
    atomicNumber: 59,
    name: 'Praseodymium',
    name_bn: 'প্রাসিওডিমিয়াম',
    symbol: 'Pr',
    mass: 140.91,
    protons: 59,
    neutrons: 82,
    electrons: 59,
    electronConfiguration: [2, 8, 18, 21, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২১', '৮', '২'],
  },
  {
    atomicNumber: 60,
    name: 'Neodymium',
    name_bn: 'নিওডিমিয়াম',
    symbol: 'Nd',
    mass: 144.24,
    protons: 60,
    neutrons: 84,
    electrons: 60,
    electronConfiguration: [2, 8, 18, 22, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২২', '৮', '২'],
  },
  {
    atomicNumber: 61,
    name: 'Promethium',
    name_bn: 'প্রমিথিয়াম',
    symbol: 'Pm',
    mass: 145,
    protons: 61,
    neutrons: 84,
    electrons: 61,
    electronConfiguration: [2, 8, 18, 23, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৩', '৮', '২'],
  },
  {
    atomicNumber: 62,
    name: 'Samarium',
    name_bn: 'সামারিয়াম',
    symbol: 'Sm',
    mass: 150.36,
    protons: 62,
    neutrons: 88,
    electrons: 62,
    electronConfiguration: [2, 8, 18, 24, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৪', '৮', '২'],
  },
  {
    atomicNumber: 63,
    name: 'Europium',
    name_bn: 'ইউরোপিয়াম',
    symbol: 'Eu',
    mass: 151.96,
    protons: 63,
    neutrons: 89,
    electrons: 63,
    electronConfiguration: [2, 8, 18, 25, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৫', '৮', '২'],
  },
  {
    atomicNumber: 64,
    name: 'Gadolinium',
    name_bn: 'গ্যাডালিনিয়াম',
    symbol: 'Gd',
    mass: 157.25,
    protons: 64,
    neutrons: 93,
    electrons: 64,
    electronConfiguration: [2, 8, 18, 25, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৫', '৯', '২'],
  },
  {
    atomicNumber: 65,
    name: 'Terbium',
    name_bn: 'টারবিয়াম',
    symbol: 'Tb',
    mass: 158.93,
    protons: 65,
    neutrons: 94,
    electrons: 65,
    electronConfiguration: [2, 8, 18, 27, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৭', '৮', '২'],
  },
  {
    atomicNumber: 66,
    name: 'Dysprosium',
    name_bn: 'ডিসপ্রোসিয়াম',
    symbol: 'Dy',
    mass: 162.50,
    protons: 66,
    neutrons: 97,
    electrons: 66,
    electronConfiguration: [2, 8, 18, 28, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৮', '৮', '২'],
  },
  {
    atomicNumber: 67,
    name: 'Holmium',
    name_bn: 'হোলমিয়াম',
    symbol: 'Ho',
    mass: 164.93,
    protons: 67,
    neutrons: 98,
    electrons: 67,
    electronConfiguration: [2, 8, 18, 29, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '২৯', '৮', '২'],
  },
  {
    atomicNumber: 68,
    name: 'Erbium',
    name_bn: 'আরবিয়াম',
    symbol: 'Er',
    mass: 167.26,
    protons: 68,
    neutrons: 99,
    electrons: 68,
    electronConfiguration: [2, 8, 18, 30, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩০', '৮', '২'],
  },
  {
    atomicNumber: 69,
    name: 'Thulium',
    name_bn: 'থুলিয়াম',
    symbol: 'Tm',
    mass: 168.93,
    protons: 69,
    neutrons: 100,
    electrons: 69,
    electronConfiguration: [2, 8, 18, 31, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩১', '৮', '২'],
  },
  {
    atomicNumber: 70,
    name: 'Ytterbium',
    name_bn: 'ইটারবিয়াম',
    symbol: 'Yb',
    mass: 173.05,
    protons: 70,
    neutrons: 103,
    electrons: 70,
    electronConfiguration: [2, 8, 18, 32, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৮', '২'],
  },
  {
    atomicNumber: 71,
    name: 'Lutetium',
    name_bn: 'লুটেটিয়াম',
    symbol: 'Lu',
    mass: 174.97,
    protons: 71,
    neutrons: 104,
    electrons: 71,
    electronConfiguration: [2, 8, 18, 32, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৯', '২'],
  },
  {
    atomicNumber: 72,
    name: 'Hafnium',
    name_bn: 'হ্যাফনিয়াম',
    symbol: 'Hf',
    mass: 178.49,
    protons: 72,
    neutrons: 106,
    electrons: 72,
    electronConfiguration: [2, 8, 18, 32, 10, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১০', '২'],
  },
  {
    atomicNumber: 73,
    name: 'Tantalum',
    name_bn: 'ট্যান্টালাম',
    symbol: 'Ta',
    mass: 180.95,
    protons: 73,
    neutrons: 108,
    electrons: 73,
    electronConfiguration: [2, 8, 18, 32, 11, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১১', '২'],
  },
  {
    atomicNumber: 74,
    name: 'Tungsten',
    name_bn: 'টাংস্টেন',
    symbol: 'W',
    mass: 183.84,
    protons: 74,
    neutrons: 110,
    electrons: 74,
    electronConfiguration: [2, 8, 18, 32, 12, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১২', '২'],
  },
  {
    atomicNumber: 75,
    name: 'Rhenium',
    name_bn: 'রেনিয়াম',
    symbol: 'Re',
    mass: 186.21,
    protons: 75,
    neutrons: 111,
    electrons: 75,
    electronConfiguration: [2, 8, 18, 32, 13, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৩', '২'],
  },
  {
    atomicNumber: 76,
    name: 'Osmium',
    name_bn: 'অসমিয়াম',
    symbol: 'Os',
    mass: 190.23,
    protons: 76,
    neutrons: 114,
    electrons: 76,
    electronConfiguration: [2, 8, 18, 32, 14, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৪', '২'],
  },
  {
    atomicNumber: 77,
    name: 'Iridium',
    name_bn: 'ইরিডিয়াম',
    symbol: 'Ir',
    mass: 192.22,
    protons: 77,
    neutrons: 115,
    electrons: 77,
    electronConfiguration: [2, 8, 18, 32, 15, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৫', '২'],
  },
  {
    atomicNumber: 78,
    name: 'Platinum',
    name_bn: 'প্লাটিনাম',
    symbol: 'Pt',
    mass: 195.08,
    protons: 78,
    neutrons: 117,
    electrons: 78,
    electronConfiguration: [2, 8, 18, 32, 17, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৭', '১'],
  },
  {
    atomicNumber: 79,
    name: 'Gold',
    name_bn: 'সোনা',
    symbol: 'Au',
    mass: 196.97,
    protons: 79,
    neutrons: 118,
    electrons: 79,
    electronConfiguration: [2, 8, 18, 32, 18, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '১'],
  },
  {
    atomicNumber: 80,
    name: 'Mercury',
    name_bn: 'পারদ',
    symbol: 'Hg',
    mass: 200.59,
    protons: 80,
    neutrons: 121,
    electrons: 80,
    electronConfiguration: [2, 8, 18, 32, 18, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '২'],
  },
  {
    atomicNumber: 81,
    name: 'Thallium',
    name_bn: 'থ্যালিয়াম',
    symbol: 'Tl',
    mass: 204.38,
    protons: 81,
    neutrons: 123,
    electrons: 81,
    electronConfiguration: [2, 8, 18, 32, 18, 3],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৩'],
  },
  {
    atomicNumber: 82,
    name: 'Lead',
    name_bn: 'সীসা',
    symbol: 'Pb',
    mass: 207.2,
    protons: 82,
    neutrons: 125,
    electrons: 82,
    electronConfiguration: [2, 8, 18, 32, 18, 4],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৪'],
  },
  {
    atomicNumber: 83,
    name: 'Bismuth',
    name_bn: 'বিসমাথ',
    symbol: 'Bi',
    mass: 208.98,
    protons: 83,
    neutrons: 126,
    electrons: 83,
    electronConfiguration: [2, 8, 18, 32, 18, 5],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৫'],
  },
  {
    atomicNumber: 84,
    name: 'Polonium',
    name_bn: 'পোলোনিয়াম',
    symbol: 'Po',
    mass: 209,
    protons: 84,
    neutrons: 125,
    electrons: 84,
    electronConfiguration: [2, 8, 18, 32, 18, 6],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৬'],
  },
  {
    atomicNumber: 85,
    name: 'Astatine',
    name_bn: 'অ্যাস্টাটিন',
    symbol: 'At',
    mass: 210,
    protons: 85,
    neutrons: 125,
    electrons: 85,
    electronConfiguration: [2, 8, 18, 32, 18, 7],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৭'],
  },
  {
    atomicNumber: 86,
    name: 'Radon',
    name_bn: 'র্যাডন',
    symbol: 'Rn',
    mass: 222,
    protons: 86,
    neutrons: 136,
    electrons: 86,
    electronConfiguration: [2, 8, 18, 32, 18, 8],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৮'],
  },
  {
    atomicNumber: 87,
    name: 'Francium',
    name_bn: 'ফ্রান্সিয়াম',
    symbol: 'Fr',
    mass: 223,
    protons: 87,
    neutrons: 136,
    electrons: 87,
    electronConfiguration: [2, 8, 18, 32, 18, 8, 1],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৮', '১'],
  },
  {
    atomicNumber: 88,
    name: 'Radium',
    name_bn: 'র‍্যাডিয়াম',
    symbol: 'Ra',
    mass: 226,
    protons: 88,
    neutrons: 138,
    electrons: 88,
    electronConfiguration: [2, 8, 18, 32, 18, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৮', '২'],
  },
  {
    atomicNumber: 89,
    name: 'Actinium',
    name_bn: 'অ্যাক্টিনিয়াম',
    symbol: 'Ac',
    mass: 227,
    protons: 89,
    neutrons: 138,
    electrons: 89,
    electronConfiguration: [2, 8, 18, 32, 18, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '৯', '২'],
  },
  {
    atomicNumber: 90,
    name: 'Thorium',
    name_bn: 'থোরিয়াম',
    symbol: 'Th',
    mass: 232.04,
    protons: 90,
    neutrons: 142,
    electrons: 90,
    electronConfiguration: [2, 8, 18, 32, 18, 10, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '১৮', '১০', '২'],
  },
  {
    atomicNumber: 91,
    name: 'Protactinium',
    name_bn: 'প্রোটেক্টিনিয়াম',
    symbol: 'Pa',
    mass: 231.04,
    protons: 91,
    neutrons: 140,
    electrons: 91,
    electronConfiguration: [2, 8, 18, 32, 20, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২০', '৯', '২'],
  },
  {
    atomicNumber: 92,
    name: 'Uranium',
    name_bn: 'ইউরেনিয়াম',
    symbol: 'U',
    mass: 238.03,
    protons: 92,
    neutrons: 146,
    electrons: 92,
    electronConfiguration: [2, 8, 18, 32, 21, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২১', '৯', '২'],
  },
  {
    atomicNumber: 93,
    name: 'Neptunium',
    name_bn: 'নেপচুনিয়াম',
    symbol: 'Np',
    mass: 237,
    protons: 93,
    neutrons: 144,
    electrons: 93,
    electronConfiguration: [2, 8, 18, 32, 22, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২২', '৯', '২'],
  },
  {
    atomicNumber: 94,
    name: 'Plutonium',
    name_bn: 'প্লুটোনিয়াম',
    symbol: 'Pu',
    mass: 244,
    protons: 94,
    neutrons: 150,
    electrons: 94,
    electronConfiguration: [2, 8, 18, 32, 24, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৪', '৮', '২'],
  },
  {
    atomicNumber: 95,
    name: 'Americium',
    name_bn: 'আমেরিসিয়াম',
    symbol: 'Am',
    mass: 243,
    protons: 95,
    neutrons: 148,
    electrons: 95,
    electronConfiguration: [2, 8, 18, 32, 25, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৫', '৮', '২'],
  },
  {
    atomicNumber: 96,
    name: 'Curium',
    name_bn: 'কুরিয়াম',
    symbol: 'Cm',
    mass: 247,
    protons: 96,
    neutrons: 151,
    electrons: 96,
    electronConfiguration: [2, 8, 18, 32, 25, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৫', '৯', '২'],
  },
  {
    atomicNumber: 97,
    name: 'Berkelium',
    name_bn: 'বার্কলিয়াম',
    symbol: 'Bk',
    mass: 247,
    protons: 97,
    neutrons: 150,
    electrons: 97,
    electronConfiguration: [2, 8, 18, 32, 27, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৭', '৮', '২'],
  },
  {
    atomicNumber: 98,
    name: 'Californium',
    name_bn: 'ক্যালিফোর্নিয়াম',
    symbol: 'Cf',
    mass: 251,
    protons: 98,
    neutrons: 153,
    electrons: 98,
    electronConfiguration: [2, 8, 18, 32, 28, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৮', '৮', '২'],
  },
  {
    atomicNumber: 99,
    name: 'Einsteinium',
    name_bn: 'আইনস্টাইনিয়াম',
    symbol: 'Es',
    mass: 252,
    protons: 99,
    neutrons: 153,
    electrons: 99,
    electronConfiguration: [2, 8, 18, 32, 29, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '২৯', '৮', '২'],
  },
  {
    atomicNumber: 100,
    name: 'Fermium',
    name_bn: 'ফার্মিয়াম',
    symbol: 'Fm',
    mass: 257,
    protons: 100,
    neutrons: 157,
    electrons: 100,
    electronConfiguration: [2, 8, 18, 32, 30, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩০', '৮', '২'],
  },
  {
    atomicNumber: 101,
    name: 'Mendelevium',
    name_bn: 'মেন্ডেলিভিয়াম',
    symbol: 'Md',
    mass: 258,
    protons: 101,
    neutrons: 157,
    electrons: 101,
    electronConfiguration: [2, 8, 18, 32, 31, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩১', '৮', '২'],
  },
  {
    atomicNumber: 102,
    name: 'Nobelium',
    name_bn: 'নোবেলিয়াম',
    symbol: 'No',
    mass: 259,
    protons: 102,
    neutrons: 157,
    electrons: 102,
    electronConfiguration: [2, 8, 18, 32, 32, 8, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '৮', '২'],
  },
  {
    atomicNumber: 103,
    name: 'Lawrencium',
    name_bn: 'লরেনসিয়াম',
    symbol: 'Lr',
    mass: 262,
    protons: 103,
    neutrons: 159,
    electrons: 103,
    electronConfiguration: [2, 8, 18, 32, 32, 9, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '৯', '২'],
  },
  {
    atomicNumber: 104,
    name: 'Rutherfordium',
    name_bn: 'রাদারফোর্ডিয়াম',
    symbol: 'Rf',
    mass: 267,
    protons: 104,
    neutrons: 163,
    electrons: 104,
    electronConfiguration: [2, 8, 18, 32, 32, 10, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১০', '২'],
  },
  {
    atomicNumber: 105,
    name: 'Dubnium',
    name_bn: 'ডুবনিয়াম',
    symbol: 'Db',
    mass: 268,
    protons: 105,
    neutrons: 163,
    electrons: 105,
    electronConfiguration: [2, 8, 18, 32, 32, 11, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১১', '২'],
  },
  {
    atomicNumber: 106,
    name: 'Seaborgium',
    name_bn: 'সিবোর্গিয়াম',
    symbol: 'Sg',
    mass: 271,
    protons: 106,
    neutrons: 165,
    electrons: 106,
    electronConfiguration: [2, 8, 18, 32, 32, 12, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১২', '২'],
  },
  {
    atomicNumber: 107,
    name: 'Bohrium',
    name_bn: 'বোরিয়াম',
    symbol: 'Bh',
    mass: 272,
    protons: 107,
    neutrons: 165,
    electrons: 107,
    electronConfiguration: [2, 8, 18, 32, 32, 13, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৩', '২'],
  },
  {
    atomicNumber: 108,
    name: 'Hassium',
    name_bn: 'হ্যাসিয়াম',
    symbol: 'Hs',
    mass: 277,
    protons: 108,
    neutrons: 169,
    electrons: 108,
    electronConfiguration: [2, 8, 18, 32, 32, 14, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৪', '২'],
  },
  {
    atomicNumber: 109,
    name: 'Meitnerium',
    name_bn: 'মাইটনারিয়াম',
    symbol: 'Mt',
    mass: 276,
    protons: 109,
    neutrons: 167,
    electrons: 109,
    electronConfiguration: [2, 8, 18, 32, 32, 15, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৫', '২'],
  },
  {
    atomicNumber: 110,
    name: 'Darmstadtium',
    name_bn: 'ডার্মস্টেটিয়াম',
    symbol: 'Ds',
    mass: 281,
    protons: 110,
    neutrons: 171,
    electrons: 110,
    electronConfiguration: [2, 8, 18, 32, 32, 16, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৬', '২'],
  },
  {
    atomicNumber: 111,
    name: 'Roentgenium',
    name_bn: 'রন্টজেনিয়াম',
    symbol: 'Rg',
    mass: 280,
    protons: 111,
    neutrons: 169,
    electrons: 111,
    electronConfiguration: [2, 8, 18, 32, 32, 17, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৭', '২'],
  },
  {
    atomicNumber: 112,
    name: 'Copernicium',
    name_bn: 'কোপার্নিসিয়াম',
    symbol: 'Cn',
    mass: 285,
    protons: 112,
    neutrons: 173,
    electrons: 112,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 2],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '২'],
  },
  {
    atomicNumber: 113,
    name: 'Nihonium',
    name_bn: 'নিহোনিয়াম',
    symbol: 'Nh',
    mass: 284,
    protons: 113,
    neutrons: 171,
    electrons: 113,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 3],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৩'],
  },
  {
    atomicNumber: 114,
    name: 'Flerovium',
    name_bn: 'ফ্লেরোভিয়াম',
    symbol: 'Fl',
    mass: 289,
    protons: 114,
    neutrons: 175,
    electrons: 114,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 4],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৪'],
  },
  {
    atomicNumber: 115,
    name: 'Moscovium',
    name_bn: 'মস্কোভিয়াম',
    symbol: 'Mc',
    mass: 288,
    protons: 115,
    neutrons: 173,
    electrons: 115,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 5],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৫'],
  },
  {
    atomicNumber: 116,
    name: 'Livermorium',
    name_bn: 'লিভারমোরিয়াম',
    symbol: 'Lv',
    mass: 293,
    protons: 116,
    neutrons: 177,
    electrons: 116,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 6],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৬'],
  },
  {
    atomicNumber: 117,
    name: 'Tennessine',
    name_bn: 'টেনেসাইন',
    symbol: 'Ts',
    mass: 294,
    protons: 117,
    neutrons: 177,
    electrons: 117,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 7],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৭'],
  },
  {
    atomicNumber: 118,
    name: 'Oganesson',
    name_bn: 'ওগানেসন',
    symbol: 'Og',
    mass: 294,
    protons: 118,
    neutrons: 176,
    electrons: 118,
    electronConfiguration: [2, 8, 18, 32, 32, 18, 8],
    electronConfiguration_bn: ['২', '৮', '১৮', '৩২', '৩২', '১৮', '৮'],
  },
];
